package:
  name: python
  version: "3.12"

source:
  git_url: ./cpython
  git_rev: HEAD
  git_depth: 0

build:
  number: 0
  string: o0_{{ PKG_BUILDNUM }}

requirements:
  build:
    - pkg-config
    - make
  host:
    - libffi
    - openssl
    - zlib
    - bzip2
    - xz
    - gdbm
    - sqlite
    - readline
    - ncurses
    - tk
    - libuuid
    - libnsl
    - xorg-libx11
    - libnsl
    - libtirpc
  run:
    - libffi
    - openssl
    - zlib
    - bzip2
    - xz
    - gdbm
    - sqlite
    - readline
    - ncurses
    - tk
    - libuuid
    - libnsl
    - xorg-libx11
    - libnsl
    - libtirpc

about:
  home: https://www.python.org/
  license: PSF
  summary: "Custom-built CPython for my tweaks"
