package:
  name: python
  version: "3.12"

source:
  path: ./cpython

build:
  number: 0
  string: o0_{{ PKG_BUILDNUM }}
  script: |
    git switch 3.12
    export CFLAGS="-g3 -O0 -gdwarf-2 -I${PREFIX}/include"
    export LDFLAGS="-L${PREFIX}/lib"
    mkdir build && cd build
    ../configure --prefix=$PREFIX --with-pydebug --with-assertions --enable-shared --with-openssl=$PREFIX || exit 1
    make -j$(nproc) || exit 1
    ln -s build/python3 build/python
    make install -j$(nproc)

requirements:
  host:
    - libffi
    - openssl
  run:
    - libffi
    - openssl

about:
  home: https://www.python.org/
  license: PSF
  summary: "Custom-built CPython for my tweaks"
